<div class="jumbotron text-center">
    <h1><?php echo sprintf($this->translate('Welcome!')) ?></h1>
    <p>In this is a demo application used to show how to do some stuff with Zend Framework 2 forms</p>
    <hr/>
    <p>The first form is working</p>
    <p><a class="btn btn-success btn-lg" href="/application/Index/testDemoFormOne"><?php echo $this->translate('Test Demo Form 1') ?></a></p>
    <hr/>
    <p>The first form is not working</p>
    <p><a class="btn btn-success btn-lg" href="/application/Index/testDemoFormTwo"><?php echo $this->translate('Test Demo Form 2') ?></a></p>
    <hr/>
    <p>Form with custom DivElement</p>
    <p><a class="btn btn-success btn-lg" href="/application/Index/testFormWithDivElement"><?php echo $this->translate('Show me the form') ?></a></p>
</div>
