<div class="jumbotron text-center">
    <h1><?php echo sprintf($this->translate('Welcome to the form element initializer test!')) ?></h1>
    <hr/>
    <p>The first form is working</p>
    <p><a class="btn btn-success btn-lg" href="/application/Index/testDemoFormOne"><?php echo $this->translate('Test Demo Form 1') ?></a></p>
    <hr/>
    <p>The first form is not working</p>
    <p><a class="btn btn-success btn-lg" href="/application/Index/testDemoFormTwo"><?php echo $this->translate('Test Demo Form 2') ?></a></p>
</div>
